services:
  clientsvh:
    image: ${DOCKER_REGISTRY-}clientsvh
    build:
      context: ${PWD}/ClientSVH
      dockerfile: ClientSVH\Dockerfile
    environment:
     - ASPNETCORE_ENVIROMENT =Development
    ports:
     - "5000:80"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "clientsvhdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "studadmin"
    ports:
       - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: studadmin
        MONGO_INITDB_ROOT_PASSWORD: studadmin
    ports:
       -  27017:27017
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: studadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: studadmin
    depends_on:
      - mongo  
 
volumes:
  postgres-db:
    driver: local
  mongodb-data:

