services:
  clientsvh:
    image: ${DOCKER_REGISTRY-}clientsvh
    build:
      context: .
      dockerfile: ClientSVH/Dockerfile
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "clientsvhdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "studadmin"
    ports:
       - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: studadmin
        MONGO_INITDB_ROOT_PASSWORD: studadmin
    ports:
       -  27017:27017
 
volumes:
  postgres-db:
    driver: local
  mongodb-data: