services:
  clientsvh:
    image: ${DOCKER_REGISTRY-}clientsvh
    build:
      context: .
      dockerfile: ClientSVH\Dockerfile
    environment:
     - ASPNETCORE_ENVIROMENT =Development
    ports:
     - "5000:80"
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "clientsvhdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "studadmin"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: studadmin
        MONGO_INITDB_ROOT_PASSWORD: studadmin
    ports:
       -  27017:27017
    volumes:
       - mongodb-data:/var/lib/mongodb/data
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
       -  8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: studadmin
        ME_CONFIG_MONGODB_ADMINPASSWORD: studadmin
        ME_CONFIG_MONGODB_URL: mongodb://studadmin:studadmin@mongo:27017/
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ENABLE_ADMIN: false
        ME_CONFIG_MONGODB_AUTH_DATABASE: docbodysvh
        ME_CONFIG_MONGODB_AUTH_USERNAME: studadmin
        ME_CONFIG_MONGODB_AUTH_PASSWORD: studadmin
        ME_CONFIG_BASICAUTH_USERNAME: studadmin
        ME_CONFIG_BASICAUTH_PASSWORD: studadmin
volumes:
  postgres-data:
  mongodb-data: